version: '2'

services:
  certbot:
    build:
      context:
        ./certbot
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ../web-root/letsencrypt:/var/www/letsencrypt
  nginx:
    build:
      context:
        ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../web-root:/var/www:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites/:/etc/nginx/sites-available:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    restart: always
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../web-root:/var/www:ro
    restart: always
  database:
    build:
      context: ./database
    volumes:
      - ./database/files:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=primary
      - MYSQL_USER=some_user_name
      - MYSQL_PASSWORD=user_pass
      - MYSQL_ROOT_PASSWORD=root_pass
    restart: always

