version: '3'

services:
  certbot:
    build:
      context:
        ./certbot
    volumes:
      - ../volumes/certbot/:/etc/letsencrypt
      - ../web-root/letsencrypt:/var/www/letsencrypt
    depends_on:
      - nginx
  login:
    build:
      context:
        ./ssh
    ports:
      - "2200:22"
    volumes:
      - ../web-root:/var/www
      - ../volumes/ssh/home:/home
      - ../volumes/ssh/shadow:/etc/shadow
      - ../volumes/ssh/passwd:/etc/passwd
      - ../volumes/ssh/group:/etc/group
      - ./ssh/sshd_config:/etc/ssh/sshd_config:ro
  nginx:
    build:
      context:
        ./nginx
    ports:
      - "80:8080"
      - "443:4433"
    volumes:
      - ../web-root:/var/www:ro
      - ../volumes/certbot:/etc/letsencrypt:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites/:/etc/nginx/sites-available:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
    restart: always
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./php-fpm
    expose:
      - "9000"
    volumes:
      - ../web-root:/var/www
    user: www-data
    restart: always
  database:
    build:
      context: ./database
    volumes:
      - ../volumes/database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=primary
      - MYSQL_USER=some_user_name
      - MYSQL_PASSWORD=user_pass
      - MYSQL_ROOT_PASSWORD=root_pass
    restart: always

