#!/bin/sh

############################################################
# Script to restart certbot.
#
# To install:
#   1. chmod +x docker-restart-certbot
#   2. cp docker-restart-certbot /etc/cron.daily/
############################################################

/usr/bin/docker restart web-hosting_certbot_1
